### ISSUE TITLE
Crash when double tapping donut

### ISSUE THREAD

**Issue by satur9nine** [android/architecture-components-samples#1027]
@chethaase 

In MADSkillsNavigationSample, just double tap the donut quickly and the app crashes:

```
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: FATAL EXCEPTION: main
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: Process: com.android.samples.navdonutcreator, PID: 6880
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: java.lang.IllegalArgumentException: Navigation action/destination com.android.samples.navdonutcreator:id/action_donutList_to_donutEntryDialogFragment cannot be found from the current destination Destination(com.android.samples.navdonutcreator:id/donutEntryDialogFragment) label=DonutEntryDialogFragment
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:931)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:868)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:854)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:1107)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at com.android.samples.donuttracker.DonutList$onViewCreated$2.onClick(DonutList.kt:64)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.view.View.performClick(View.java:7259)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7236)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.view.View.access$3600(View.java:801)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27896)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-10-08 09:42:27.752  6880  6880 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by gmikhail** [comment]
Because the problem is more global, I decided to create an issue in the official bug tracker. I will be glad to your thoughts.

https://issuetracker.google.com/issues/271303578
