### ISSUE TITLE
What will case "Can't access ViewModels from onDestroy" and how to solve it gracefully?

### ISSUE THREAD

**Issue by XinyueZ** [android/architecture-components-samples#256]
java.lang.RuntimeException: Unable to destroy activity {xxxxxx}: java.lang.IllegalStateException: Can't access ViewModels from onDestroy

**Comment by AndrewWestberg** [comment]
I've seen this issue when using ViewModels inside of a RecyclerView holder while backgrounding/foregrounding an app. Haven't figured out how to solve it yet though.

**Comment by AndrewWestberg** [comment]
`java.lang.IllegalStateException: Can't access ViewModels from onDestroy
at android.arch.lifecycle.HolderFragment$HolderFragmentManager.findHolderFragment(HolderFragment.java:139)
at android.arch.lifecycle.HolderFragment$HolderFragmentManager.holderFragmentFor(HolderFragment.java:158)
at android.arch.lifecycle.HolderFragment.holderFragmentFor(HolderFragment.java:84)
at android.arch.lifecycle.ViewModelStores.of(ViewModelStores.java:47)
at android.arch.lifecycle.ViewModelProviders.of(ViewModelProviders.java:124)
at com.example.adapter.MyViewHolder.<init>(MyViewHolder.java:111)`

**Comment by Guang1234567** [comment]
@AndrewWestberg 

Why call `ViewModelproviders.of(activity or fragment).get(XxxxViewModel.class)` in RecyclerView's adapter?

**Comment by Guang1234567** [comment]
why not 

```java
class XxxAdapter {
      public XxxAdapter(XxxViewmodel vm) {

      }
}

```

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still having an issue.
