### ISSUE TITLE
crash:Failed resolution of: Landroid/arch/lifecycle/GeneratedAdapter

### ISSUE THREAD

**Issue by zhengcx** [android/architecture-components-samples#342]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/GeneratedAdapter;
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:400)
 at java.lang.Class.forName(Class.java:326)
 at android.arch.lifecycle.Lifecycling.getGeneratedAdapterConstructor(Lifecycling.java:96)
 at android.arch.lifecycle.Lifecycling.getGeneratedAdapterConstructor(Lifecycling.java:102)
 at android.arch.lifecycle.Lifecycling.getCallback(Lifecycling.java:61)
 at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:319)
 at android.arch.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:145)
 at OrderDetailMapActivity.initViews(OrderDetailMapActivity.java:86)
 at BaseToolbarActivity.setView(BaseToolbarActivity.java:78)
 at BaseToolbarActivity.onCreate(BaseToolbarActivity.java:68)
 at android.app.Activity.performCreate(Activity.java:6977)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
 at android.app.ActivityThread.-wrap14(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6823)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.GeneratedAdapter" on path: DexPathList[[zip file "/data/app/ctrip.english.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/ctrip.english.debug-1/lib/arm, /data/app/ctrip.english.debug-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 ... 23 more

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with these samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still having an issue.
