### ISSUE TITLE
Run-time error due to lack of Class_Imp, how to solve?

### ISSUE THREAD

**Issue by DaniloFurtado** [android/architecture-components-samples#393]
My project does build successfully, but when I run to run on my device it throws the following error saying it did not find the RegisterAppDataBase_Impl class. How to solve this.
My Code.

`
@Database(entities = [Product::class], version = 1)
abstract class RegisterAppDataBase: RoomDatabase() {
    abstract fun registerDao(): ProductRegisterDao
    abstract fun listDao(): ProductListDao

    companion object {
        private var INSTANCE: RegisterAppDataBase? = null

        fun getInstance(context: Context): RegisterAppDataBase? {
            if (INSTANCE == null) {
                synchronized(RegisterAppDataBase::class) {
                    INSTANCE = Room.databaseBuilder(context.applicationContext,
                            RegisterAppDataBase::class.java, RegisterAppDataBase::class.java.simpleName+".db")
                            .fallbackToDestructiveMigration()
                            .build()
                }
            }
            return INSTANCE
        }

        fun destroyInstance() {
            INSTANCE = null
        }
    }
}`

Error 

`2018-06-10 16:38:42.812 967-967/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: produtc.register.com, PID: 967
    java.lang.RuntimeException: Unable to create application produtc.register.com.RegisterApplication: java.lang.RuntimeException: cannot find implementation for produtc.register.com.data.database.RegisterAppDataBase. RegisterAppDataBase_Impl does not exist
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.RuntimeException: cannot find implementation for produtc.register.com.data.database.RegisterAppDataBase. RegisterAppDataBase_Impl does not exist
        at androidx.room.Room.getGeneratedImplementation(Room.java:94)
        at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:631)
        at produtc.register.com.data.database.RegisterAppDataBase$Companion.getInstance(RegisterAppDataBase.kt:27)
        at produtc.register.com.RegisterApplication.onCreate(RegisterApplication.kt:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5402)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
`

**Comment by Kostanos** [comment]
I have the same error. Did you find the solution?

**Comment by DaniloFurtado** [comment]
@kostanos
I don't remember exactly what I did, but I fixed it.
Look my project, this error was happening in this project and now it's work.

https://github.com/DaniloFurtado/CrudProject/tree/master/app/src/main/java/com/crudproject/data

**Comment by noelstieglitz** [comment]
@Kostanos I found [this](https://stackoverflow.com/a/44095904/301703
) SO answer resolved the error for me, specifically adding these to gradle:

```
implementation "android.arch.persistence.room:runtime:$room_version"
annotationProcessor "android.arch.persistence.room:compiler:$room_version"
kapt "android.arch.persistence.room:compiler:$room_version"
```

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
