### ISSUE TITLE
PagingWithNetworkSample crashes when loading new data from network

### ISSUE THREAD

**Issue by Tenkei** [android/architecture-components-samples#401]
To reproduce the problem:
1. Enter Application
2. Select Network Only (Anything works but it's more likely to happen when you only work with network)
3. Search Something
4. Pull-to-refresh multiple time

observations: The problem seems related to network connection speed.

the crash log:
```

06-24 11:19:25.576 23593-23593/com.android.example.paging.pagingwithnetwork E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.android.example.paging.pagingwithnetwork, PID: 23593
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter author
  at com.android.example.paging.pagingwithnetwork.reddit.vo.RedditPost.copy(Unknown Source:18)
  at com.android.example.paging.pagingwithnetwork.reddit.vo.RedditPost.copy$default(Unknown Source:91)
  at com.android.example.paging.pagingwithnetwork.reddit.ui.PostsAdapter$Companion.sameExceptScore(PostsAdapter.kt:116)
  at com.android.example.paging.pagingwithnetwork.reddit.ui.PostsAdapter$Companion.access$sameExceptScore(PostsAdapter.kt:94)
  at com.android.example.paging.pagingwithnetwork.reddit.ui.PostsAdapter$Companion$POST_COMPARATOR$1.getChangePayload(PostsAdapter.kt:104)
  at com.android.example.paging.pagingwithnetwork.reddit.ui.PostsAdapter$Companion$POST_COMPARATOR$1.getChangePayload(PostsAdapter.kt:96)
  at android.arch.paging.PagedStorageDiffHelper$1.getChangePayload(PagedStorageDiffHelper.java:46)
  at android.support.v7.util.DiffUtil$DiffResult.dispatchUpdatesTo(DiffUtil.java:775)
  at android.arch.paging.PagedStorageDiffHelper.dispatchDiff(PagedStorageDiffHelper.java:147)
  at android.arch.paging.AsyncPagedListDiffer.latchPagedList(AsyncPagedListDiffer.java:327)
  at android.arch.paging.AsyncPagedListDiffer.access$300(AsyncPagedListDiffer.java:116)
  at android.arch.paging.AsyncPagedListDiffer$2$1.run(AsyncPagedListDiffer.java:307)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:172)
  at android.app.ActivityThread.main(ActivityThread.java:6637)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by dlam** [comment]
Closing as obsolete after Paging3 upgrade.
