### ISSUE TITLE
LifecycleRegistry NullPointerException

### ISSUE THREAD

**Issue by YouriZhang** [android/architecture-components-samples#430]
Hello,we use 'android.arch.lifecycle:extensions:1.1.1' in our android project,but there occurred NullPointerException in method  handleLifecycleEvent(@NonNull Lifecycle.Event event) of LifecycleRegistry.  see logs below:
![image](https://user-images.githubusercontent.com/23033652/43498021-9266a5e2-9577-11e8-9771-3cbf5faee00a.png)

![image](https://user-images.githubusercontent.com/23033652/43497844-c378b6f8-9576-11e8-9c1a-72392e3d7e53.png)

**Comment by YouriZhang** [comment]
Has the new version of this component solved this issue ?

**Comment by sohailniazai** [comment]
I am also facing this issue in version 1.1.0. Any update on this issue?

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map$Entry.getValue()' on a null object reference
   at android.arch.lifecycle.LifecycleRegistry.isSynced(LifecycleRegistry.java:146)
   at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:323)
   at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
   at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
   at android.support.v4.app.Fragment.performResume(Fragment.java:2396)
   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
   at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
   at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3215)
   at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
   at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
   at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
   at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
   at android.app.Activity.performResume(Activity.java:7377)
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
   at android.os.Handler.dispatchMessage(Handler.java:105)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6938)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by YouriZhang** [comment]
I realize  that  LifecycleRegistry api should  be used in android MainThread  by reading the source code，i once  use this api   in  webview  javainterface , but  it  worked not always in android MainThread, so  sometimes this issue occurred。

**Comment by YouriZhang** [comment]
I realize that LifecycleRegistry api should be used in android MainThread by reading the source code，i once use this api in webview javainterface , but it worked not always in android MainThread, so sometimes this issue occurred@sohailniazai

**Comment by liyanxi** [comment]
@sohailniazai  Have you solved it?

**Comment by ianhanniballake** [comment]
Feel free to file a bug against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if this is still a problem.
