### ISSUE TITLE
NullPointerException in WorkManagerImpl.getProcessor()

### ISSUE THREAD

**Issue by zenkhas** [android/architecture-components-samples#449]
Fatal Exception: java.lang.RuntimeException: Unable to create service androidx.work.impl.background.systemjob.SystemJobService: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.work.impl.Processor androidx.work.impl.WorkManagerImpl.getProcessor()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3146)
       at android.app.ActivityThread.access$1900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5982)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.work.impl.Processor androidx.work.impl.WorkManagerImpl.getProcessor()' on a null object reference
       at androidx.work.impl.background.systemjob.SystemJobService.onCreate(SystemJobService.java:52)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3133)
       at android.app.ActivityThread.access$1900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5982)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

Version: 1.0.0-alpha04

**Comment by ianhanniballake** [comment]
This doesn't seem like an issue with these samples. You can file an issue against WorkManager on [the issue tracker](https://issuetracker.google.com/issues/new?component=409906) if you're still having an issue.
