### ISSUE TITLE
IllegalArgumentException: Page size can change only if last page is only one present

### ISSUE THREAD

**Issue by sm-tester** [android/architecture-components-samples#458]
If you use AsyncPagedListDiffer then when user click to RecyclerView item we will get clicked item from pagedList by adapter position and we will get following crash:

`Fatal Exception: java.lang.IllegalArgumentException: Page size can change only if last page is only one present
       at android.arch.paging.PagedStorage.allocatePlaceholders(PagedStorage.java:404)
       at android.arch.paging.TiledPagedList.loadAroundInternal(TiledPagedList.java:156)
       at android.arch.paging.PagedList.loadAround(PagedList.java:398)
       at android.arch.paging.AsyncPagedListDiffer.getItem(AsyncPagedListDiffer.java:201)
       at com.my.store.helpers.adapters.products.ShowCatProductsAdapter$ProductViewHolder.lambda$new$0$ShowCatProductsAdapter$ProductViewHolder(ShowCatProductsAdapter.java:113)
       at com.my.store.helpers.adapters.products.ShowCatProductsAdapter$ProductViewHolder$$Lambda$0.onClick(Unknown Source)
       at android.view.View.performClick(View.java:5637)
       at android.view.View$PerformClick.run(View.java:22429)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

Device: General Mobile(GM 5 d)
Android: 7.1.1

Same issue from another developer : https://stackoverflow.com/questions/51013826/android-paging-library-getitem-raisesillegalargumentexception

**Comment by dlam** [comment]
Paging3 supports variable page sizes now, so this should no longer be an issue fwiw (sorry for the lack of replies as this was opened awhile ago)
