### ISSUE TITLE
LifeCycleRegistery NullPointerException on onStart()

### ISSUE THREAD

**Issue by sohailniazai** [android/architecture-components-samples#464]
I am using     implementation 'android.arch.lifecycle:extensions:1.1.0' and facing the following crash. Is this the lifecycle issue or app? This issue is ocurring after I have moved target sdk to 27.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
       at java.util.ArrayList.remove(ArrayList.java:405)
       at android.arch.lifecycle.LifecycleRegistry.popParentState(LifecycleRegistry.java:194)
       at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293)
       at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
       at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
       at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2377)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2214)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3143)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1599)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1891)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7501)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by moonshoter** [comment]
This also happens in my company's app。 when some Activity onDestroy().

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Lifecycle on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still having an issue.
