### ISSUE TITLE
Room with paging list: IllegalStateException: connection pool has been closed

### ISSUE THREAD

**Issue by GanapathiGarre** [android/architecture-components-samples#509]
Hi, I am using Room db with paging list to display list of items in my screen. Here is code which I am using to get the data.

**var itemsList: LiveData<PagedList<MachineInfoModel>>? = null
CustomersDataSource().getCustomerFromDb(SimpleSQLiteQuery(rawQuery))?.let {
            customerList = LivePagedListBuilder(it, PAGE_NUMBER).build()
        }
fun getCustomerFromDb(query: SimpleSQLiteQuery): DataSource.Factory<Int, CustomerInfoModel>? {
        return App.clientDatabase?.customerInfoDao().getCustomerInfoWithSearchAndFilter(query)
    }**

Everything working as expected but some times app getting crash by throwing below issue.
The db object I am using is singleton. And I am not doing any open and close operations on db object since room is going to take care of it.

Any suggestion can be helpful. Thanks.

**Fatal Exception: java.lang.IllegalStateException:** Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1198)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:808)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:534)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:904)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
       at com.test.mysample.data.local.dao.CustomerInfoModelDao_Impl$14$1.convertRows(CustomerInfoModelDao_Impl.java:4716)
       at android.arch.persistence.room.paging.LimitOffsetDataSource.loadRange(LimitOffsetDataSource.java:168)
       at android.arch.persistence.room.paging.LimitOffsetDataSource.loadInitial(LimitOffsetDataSource.java:119)
       at android.arch.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
       at android.arch.paging.TiledPagedList.<init>(TiledPagedList.java:98)
       at android.arch.paging.PagedList.create(PagedList.java:203)
       at android.arch.paging.PagedList.access$000(PagedList.java:114)
       at android.arch.paging.PagedList$Builder.build(PagedList.java:362)
       at android.arch.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:201)
       at android.arch.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:166)
       at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Room on [the issue tracker](https://issuetracker.google.com/issues/new?component=413107) if you're still having an issue.
