### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by mobDevKz** [android/architecture-components-samples#709]
Hello! Get exception when trying to finish activity and start another one. It happens only when using viewmodel scoped to a navgraph. I will be grateful for advice on how to fix this error.

private val sharedViewModel: SharedViewModel by navGraphViewModels(R.id.navigation_sample) {
    viewModelFactory
}

FATAL EXCEPTION: main
    Process: test.app, PID: 27948
    java.lang.RuntimeException: Unable to destroy activity {......ui.activities.authorized.AuthorizedActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4459)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4477)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at androidx.navigation.NavControllerViewModel.onCleared(NavControllerViewModel.java:62)
        at androidx.lifecycle.ViewModel.clear(ViewModel.java:139)
        at androidx.lifecycle.ViewModelStore.clear(ViewModelStore.java:62)
        at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigState(FragmentManagerViewModel.java:160)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1026)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at android.app.Activity.performDestroy(Activity.java:7395)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4477) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by obiwanzenobi** [comment]
Try to override onDestroy in your activity and catch concurrent exception like this:
`try {
            super.onDestroy()
        } catch (e: ConcurrentModificationException) {
            Timber.e(e)
        }`

But i encountered worse problem: 
`java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at androidx.navigation.NavControllerViewModel.onCleared(NavControllerViewModel.java:62)
       at androidx.lifecycle.ViewModel.clear(ViewModel.java:139)
       at androidx.lifecycle.ViewModelStore.clear(ViewModelStore.java:62)
       at androidx.fragment.app.FragmentManagerViewModel.clearNonConfigState(FragmentManagerViewModel.java:160)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1026)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
       at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1884)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6912)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)`

While using fragments. Still searching for resolution but there is no reference to app (only nav lib and fragment manager).

**Comment by ianhanniballake** [comment]
This doesn't seem to be an issue with the samples. You can file an issue against Fragments on [the issue tracker](https://issuetracker.google.com/issues/new?component=460964) if you're still having an issue.
