### ISSUE TITLE
How to access parent layout of <include> in View Binding

### ISSUE THREAD

**Issue by rohit6027** [android/architecture-components-samples#822]
NullPointerException while getting the id of parent layout in <include tag>

xml file :
`<include android:id="@+id/idInShareMoment" layout="@layout/layout_share_moments"/>
`

included layout :  
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/idLLShareNewMoment"
    android:layout_width="match_parent"
    android:layout_height="@dimen/_50sdp"
    android:layout_marginTop="@dimen/_10sdp"
    android:background="@color/colorWhite"
    android:gravity="center_vertical"
    android:padding="@dimen/_10sdp"/>


```//kt file
 mBinding.idInShareMoment.idLLShareNewMoment.setOnClickListener {
           //do your work
        }
``
//getting below exception
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.chessfellow/com.app.chessfellow.ui.main.MainActivity}: java.lang.NullPointerException: Missing required view with ID: idLLShareNewMoment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 

How can we access parent layout ID in <include> tag ??

**Comment by rohit6027** [comment]
Ok, no need to answer this question I got the solution.

**Comment by CoolMind** [comment]
For those who came here, see https://stackoverflow.com/questions/16734541/nullpointerexception-on-rootview-of-an-included-layout.

Use `mBinding.idInShareMoment.setOnClickListener`

**Comment by 18391610438** [comment]
> 好了，这个问题不用回答了，我已经解决了。

If using ViewBinding  How to solve

**Comment by lazy-coder-10** [comment]
@18391610438 Instead of using parent layout id you have to use root method. 
Ex. `mBinding.idInShareMoment.**root**.setOnClickListener {}`
