### ISSUE TITLE
Null pointer expection in lifecycle event in release bulid

### ISSUE THREAD

**Issue by arunabimanyu7** [android/architecture-components-samples#835]
Im Facing  this issue im using this version androidx.lifecycle:lifecycle-extensions:2.2.0'

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map$Entry.getValue()' on a null object reference
       at androidx.lifecycle.LifecycleRegistry.isSynced(LifecycleRegistry.java:153)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:330)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
       at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.java:102)
       at android.app.Fragment.performActivityCreated(Fragment.java:2517)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3033)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2985)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:179)
       at android.app.Activity.performCreate(Activity.java:7264)
       at android.app.Activity.performCreate(Activity.java:7249)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2941)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7025)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by ianhanniballake** [comment]
This issue tracker is for issues with these samples, not issues with the Architecture Component libraries themselves. It looks like you've [already filed an issue](https://issuetracker.google.com/issues/155223268) on the correct issue tracker.
