### ISSUE TITLE
[PagingNetworkSample] crashes when you try to load data from db+ network initially when there is no network connection.

### ISSUE THREAD

**Issue by raghunandankavi2010** [android/architecture-components-samples#905]
Switch off mobile data and wifi. Launch the MainActivity. Click on Button db+ network. The sample crashes with

```
 Process: com.android.example.paging.pagingwithnetwork, PID: 10444
     java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.example.paging.pagingwithnetwork.reddit.vo.SubredditRemoteKey.getNextPageKey()' on a null object reference
         at com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.PageKeyedRemoteMediator.load(PageKeyedRemoteMediator.kt:47)
         at com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.PageKeyedRemoteMediator$load$1.invokeSuspend(Unknown Source:12)
         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
         at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:76)
         at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:106)
         at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:32)
         at androidx.lifecycle.DispatchQueue$runOrEnqueue$$inlined$with$lambda$1.run(DispatchQueue.kt:93)
         at android.os.Handler.handleCallback(Handler.java:938)
         at android.os.Handler.dispatchMessage(Handler.java:99)
         at android.os.Looper.loop(Looper.java:223)
         at android.app.ActivityThread.main(ActivityThread.java:7656)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

The crash points to

           

```
   if (remoteKey.nextPageKey == null) {
          return MediatorResult.Success(endOfPaginationReached = true)
   }
 
  remoteKey.nextPageKey
```

**Comment by dlam** [comment]
This should be fixed now with recent library changes that allow remote append / prepend to queue and depend on  remote refresh by returning `LAUNCH_INITIAL_REFRESH` in `RemoteMediator.initialize()`
