### ISSUE TITLE
[NavigationAdvancedSample] Support for loading navgraph in Dynamic feature module

### ISSUE THREAD

**Issue by tieren1** [android/architecture-components-samples#911]
Hi I am getting error when setting navgraph with the <include-dynamic tag which contains the navgraph within the dynamic feature module.

<?xml version="1.0" encoding="utf-8"?>
<navigation xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/included_navigation">

    <include-dynamic
        android:id="@+id/someFeatureNav"
        app:moduleName="someFeatureModule"
        app:graphResName="some_navigation"
        app:graphPackage="com.some.package" />
</navigation>

Passing the id of the navigation graph. R.navigation.included_navigation into setupWithNavController.

Error points to NavHostFragment.create

// Otherwise, create it and return it.
    val navHostFragment = NavHostFragment.create(navGraphId)
    fragmentManager.beginTransaction()
            .add(containerId, navHostFragment, fragmentTag)
            .commitNow()

Caused by: java.lang.IllegalStateException: Could not find Navigator with name "include-dynamic". You must call NavController.addN
                            avigator() for each navigation type.
                         E      at androidx.navigation.NavigatorProvider.getNavigator(NavigatorProvider.java:98)
                         E      at androidx.navigation.NavInflater.inflate(NavInflater.java:107)
                         E      at androidx.navigation.NavInflater.inflate(NavInflater.java:141)
                         E      at androidx.navigation.NavInflater.inflate(NavInflater.java:88)
                         E      ... 31 more

Since NavHostFragment.create() returns NavHostFragment instead of DynamicNavHostFrqagment.

Found similar question [here](https://stackoverflow.com/questions/62796133/how-to-use-dynamic-feature-module-with-bottomnavigationview) with a workaround by having a custom createDynamicNavHostFragment.

Is there any cleaner ways of doing this?

**Comment by yakupc** [comment]
I have same problem. There is an issue still open in the issue tracker. I hope that they will also fix navigation issue which is loading nav graph in dynamic feature modules.  
https://issuetracker.google.com/issues/80029773
